### ISSUE TITLE
"Could not load F:\tinybear\tinybearLab\rollup\libs/m1"  in windows

### ISSUE THREAD

**Issue by ideayuye** [frostney/rollup-plugin-alias#11]
config:
`export default {
  entry: 'main.js',
  dest: 'dist/bundle.js',
  format: 'umd',
  plugins: [ 
    alias({
      libs: path.resolve(__dirname, './libs')
    }),
    uglify()
  ],
};`

import code:
`import hello from "libs/m1"
import hi from "libs/m2"`

run :"rollup -c config.js -m inline"

Then, will expose an error:
`Could not load F:\tinybear\tinybearLab\rollup\libs/m1 (imported by F:\tinybear\tinybearLab\roll
up\main.js): ENOENT: no such file or directory, open 'F:\tinybear\tinybearLab\rollup\libs\m1'`

But modify import code  like this:
`import hello from "libs/m1.js"
import hi from "libs/m2.js"`

run the build command will be ok.

**Comment by ideayuye** [comment]
In windows the path will be:
`F:\tinybear\tinybearLab\rollup\libs/m1`

But the function can't support the path:
`const isFilePath = id => /^\.?\//.test(id);` 

So ,I modify the function to:
`const isFilePath = id => /(^\.?\/)|(^[a-zA-Z]\:(\\|\/))/.test(id);`

**Comment by HenriMorlaye** [comment]
Your change worked for me too on Windows 10. Thanks. Maybe this should be in a next version of this library ?

**Comment by frostney** [comment]
That's great @ideayuye @HenriMorlaye, thank you! I actually have a Win 10 machine right now for testing, let me see what I could do

**Comment by HenriMorlaye** [comment]
I was trying to build Vue.js on Windows which depends on this library. It didn't work, just changing in rollup-plugin-alias
```const isFilePath = id => /^\.?\//.test(id);```
to
```const isFilePath = id => /(^\.?\/)|(^[a-zA-Z]\:(\\|\/))/.test(id);```
made it possible to compile Vue.js for me. No idea if it creates a problem somewhere else though.

**Comment by Rich-Harris** [comment]
Hi, this repo has been adopted by the main rollup org — we've just published 1.3.0 which includes a fix for #3 which seems like it might be related to this. If you get a chance, could you check to see if this issue is fixed please? Thanks

**Comment by ideayuye** [comment]
@Rich-Harris I test the 1.3.0.Unfortunately，it still catch the error.

> [Error: Could not load F:\tinybear\tinybearLab\rollup\libs/m1 (imported by F:\tinybear\tinybearLab\rollup\main.js): ENOENT: no such file or directory, open 'F:
> \tinybear\tinybearLab\rollup\libs\m1']

Test code like this.
` "dependencies": {
    "rollup": "^0.41.6",
    "rollup-plugin-alias": "^1.3.0",
    "rollup-plugin-uglify": "^1.0.1"
  }`
build.js:
```
var rollup = require('rollup');
 var alias = require('rollup-plugin-alias');
 var path = require('path');
rollup.rollup({
    entry: 'main.js',
    plugins: [
        alias({
            libs: path.resolve(__dirname, './libs')
        })
    ]
}).then(function(bundle){
    bundle.write({
        format:'umd',
        dest: 'dist/bundle_api.js'
    });
    console.log('it build ok')
},function(error){
    console.log(error);
});
```
main.js:
```
import hello from "libs/m1"
import hi from "libs/m2"

hello();
hi();
```
libs/m1.js:
```
export default function hello(){
    console.log('it is m1');
}
```

libs/m2.js:
```
import hello from "./m1.js"
hello();

export default function hi(){
    console.log('hi');
}
```

**Comment by vjoao** [comment]
I made a change and was able to build Vue: `var filePath = updatedId;` instead of `var filePath = path.posix.resolve(directory, updatedId);`. For some reason, the plugin is injecting the full path again, giving me `/node_modules/vue/src/core/C:/.../node_modules/vue/src/core/index.js` which is really strange.
 I had to take it off from the plugin itself to be able to build Vue.

**Comment by vjoao** [comment]
I have been able to compile Vue on Windows 10 after modifying the plugin from `path.posix.resolve` to `path.resolve`.

**Comment by mhhegazy** [comment]
@ideayuye @frostney @Rich-Harris please review PR #22 and tell if it solve this issue.

**Comment by ICELI** [comment]
Come out, my master···

**Comment by frostney** [comment]
I don't think it's as easy as just merging in #22. There are #20, #21 and #22 which all seem to fix the same issue and I'm not sure I figured out the scope of it yet. Are those different implementations, do all of them need to be merged in or something else entirely?

I'm also wondering if there's some way we could check Vue and React builds on Windows in direct relation with this plugin.

@ICELI Don't get me wrong, I do understand the frustration. I don't think airing the frustration is a constructive way to resolve the issue though.

**Comment by ICELI** [comment]
Sorry~ :joy:

This issue just like build Vue on Windows. 
`isFilePath(updatedId)` will return false on Windows. Then `.js` extension will not be fixed.
There are two ways to resolve:
1. modify the RegExp in `isFilePath` function, to support `windows` path #12
2. use `normalizeId` function to fix the `windows` path（`entry` or `updatedId`）#21

**Comment by mhhegazy** [comment]
@frostney before I make PR #22, I tried all existing PR to build React on Windows. 

#18 and #21 
Give this error:
```
TypeError: Cannot read property 'specifier' of undefined
    at E:\react\node_modules\rollup\dist\rollup.js:9593:47
    at process._tickCallback (internal/process/next_tick.js:103:7)
error Command failed with exit code 1.
```

#20
build completed with different file sizes between Linux and Windows build.
here [diff between Linux build with v1.3.1 and windows build with PR #20 used](http://www.mergely.com/P5lEW94B/)

**Comment by Luobata** [comment]
I have the same exception and find it's the bug with the regex that can't match the entry begin with 'G:\' and I have submit a PR #30 .
