### ISSUE TITLE
Support for regular expression 

### ISSUE THREAD

**Issue by wang2lang** [frostney/rollup-plugin-alias#13]
// example
alias({
   resolve: ['.js'],
    'vue': 'node_modules/vue/dist/vue.common.js'
 }),

// app.js
import vue from 'vue'
import vue-router from 'vue-router'

then throw error:  Could not load node_modules/vue/dist/vue.common.js-router

maybe should borrow from webpack, just like:

'vue$': 'node_modules/vue/dist/vue.common.js'

**Comment by frostney** [comment]
I believe that's the issue that has reported in #7, which is why I'm closing the issue.

As for regular expressions as a feature, I personally think it might come at the cost of readability, but I would not be opposed to it if someone does a pull request for it.
