### ISSUE TITLE
Could not alias a module to another?

### ISSUE THREAD

**Issue by JounQin** [frostney/rollup-plugin-alias#24]
When I'm using
```
alias(
  { qrious: 'node-qrious' }
)
```

it doesn't work.

**Comment by frostney** [comment]
Hi @JounQin, could you give me some information on where `node-qrious` lives. Is it an NPM module you installed?

**Comment by JounQin** [comment]
Yes, it is an another `qrious` version which is used on node/server environment, so I need to alias `qrious` to `node-qrious` when using server side render.

For now, I'm using `rollup-plugin-replace` as workaround, but it seems not good enough.

**Comment by frostney** [comment]
I'm wondering if `node-qrious` lives in your `node_modules`. I'm guessing it does. Could you try:
```javascript
alias(
  { qrious: path.resolve(__dirname, 'node_modules', 'node-qrious') }
)
```
and let me know of the result 🙂

**Comment by JounQin** [comment]
I'm using `qrious`/`node-qrious` as external dependence, does it mean rollup will only resolve but not replace `qrious` as `node-qrious`?

**Comment by jonataswalker** [comment]
@JounQin with external dependency use [options.paths](https://github.com/rollup/rollup/wiki/JavaScript-API#paths). Also see https://github.com/rollup/rollup/issues/1285

**Comment by JounQin** [comment]
@jonataswalker Thanks for your explanation, it works well.
