### ISSUE TITLE
can't import alias for folder

### ISSUE THREAD

**Issue by plandem** [frostney/rollup-plugin-alias#26]
my alias is set for:
```
app -> ./
```
but imports like:
```js
import main from 'app/main';
```
is not working anymore. it tries to load ./main.js

**Comment by jcperez-ch** [comment]
Same issue, an `EISDIR: illegal operation on a directory, read` is happening when I alias a folder, it doesn't assume that there is a `app/main/index.js`

**Comment by simonhambly** [comment]
@plandem have you tried the adding `'/index.js'`  to the resolve option? Something like this worked for: 

```
      // in the rollup config

      plugins: [
        alias({
          app: path.resolve(cwd, './'),
          resolve: ['.js', '/index.js'] 
        })
      ]

```

**Comment by Rich-Harris** [comment]
Just do `import main from 'app/main/index.js'`. Reimplementing Node's absurd resolution algorithm is beyond the scope of this plugin 😀
