### ISSUE TITLE
Aliases not working while importing node modules

### ISSUE THREAD

**Issue by rjnair-nm** [frostney/rollup-plugin-alias#27]
I am using preact-compat as an alias for react within my rollup config file. My plugin config is as below :-

```
plugins: [
    alias({
      'react': path.resolve('./node_modules/preact-compat/dist/preact-compat.es.js'),
      'react-dom': path.resolve('./node_modules/preact-compat/dist/preact-compat.es.js')
    }),
    nodeResolve({ jsnext: true, browser: true }),
    commonjs({ include: ['node_modules/**'], namedExports: { 'preact-redux': ['connect', 'Provider'] } }),
    replace({ '__CLIENT__': true, 'process.env.NODE_ENV': JSON.stringify('production') }),
    images,
    buble({ jsx: 'h', objectAssign: 'Object.assign' }),
    !isDev && uglify(uglifyConfig) // uglify slows builds
  ]
```

With the above configuration, when i use the below code within any of my local React components file it works flawlessly. 

`import React from 'react'`

However, if i use another library (like [react-text-mask](https://github.com/text-mask/text-mask/tree/master/react)) which has dependency with React, the aliases doesn't work. 

```
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/Users/Projects/my-react-app/node_modules/react-text-mask/dist/reactTextMask.js:1:145)
    at Object.<anonymous> (/Users/Projects/my-react-app/node_modules/react-text-mask/dist/reactTextMask.js:1:315)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

Arent the alisaes supposed to work within the node_modules as well?

**Comment by webdeb** [comment]
> Arent the alisaes supposed to work within the node_modules as well?

+1

**Comment by webdeb** [comment]
It would be also nice, if this would just work:

```
"react": "preact-compat",
"react-dom": "preact-compat",
```

**Comment by Rich-Harris** [comment]
From the stack trace, it looks like Rollup isn't bundling react-text-mask into your app, which means `alias` doesn't get a chance to fix the `react` import. If that's not the case, can you provide a repro?

**Comment by DharanBro** [comment]
```
alias({
    "react": path.resolve(__dirname, 'node_modules/preact/dist/preact.js'),
    "react-dom": path.resolve(__dirname, 'node_modules/preact-compat/dist/preact-compat.js'),
}),
```

```
import React, { Component } from 'react';

export default class App extends Component {

}
```
Throws:
_'Component' is not exported by node_modules\preact\dist\preact.js_

But this works
```
import React from 'react';

export default class App extends React.Component {

}
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
