### ISSUE TITLE
Troubles with isFilePath on windows

### ISSUE THREAD

**Issue by lukeapage** [frostney/rollup-plugin-alias#3]
Hi,

I'm having trouble getting isFilePath to match on windows - and therefore am not getting extensions being resolved.

If I give an absolute resolved path to alias, the regex does not pass on windows (because its `c:\a\b` not `\a\b\`

If I give a relative path, it doesn't work because I need `../` at the begining.

I'm currently solving this by passing this alias

```
'alias': './../' + path.relative(path.resolve('.'), path_i_want)
```

perhaps the isFilePath could be `/^(\.{0,2}[\/\\]|[a-z]:\/\/)/i` - what do you think?

**Comment by lukeapage** [comment]
this is the function causing an issue
https://github.com/frostney/rollup-plugin-alias/blob/master/src/index.js#L8

**Comment by lukeapage** [comment]
My use-case was broken when I upgraded because of
https://github.com/frostney/rollup-plugin-alias/pull/2
@yyx990803

**Comment by frostney** [comment]
Hi @lukeapage, thank you for reporting the issue and I'm terribly sorry for the inconvenience. The regex looks good to me. I'm wondering if there isn't a Node.js built-in method that would do the check for us more predictably for different platforms?

**Comment by lukeapage** [comment]
The trouble is that although there is an `isAbsolute` / `isRelative` what I think you want is - isAbsolute || isRelative, but excluding module_path/...
But I didn't write that function so I'm only guessing.
You could alternately always try resolving with a file extension and _not_ add on `.js` if you fail to resolve..

**Comment by cdunford** [comment]
I am experiencing this - the pull request to resolve it works well for me.

**Comment by cool-Blue** [comment]
@Rich-Harris  I think this should still be open? The original problem with relative addresses beginning with `../` remains.
