### ISSUE TITLE
how should example in README.md be run?

### ISSUE THREAD

**Issue by ffflabs** [frostney/rollup-plugin-alias#31]
I've been using Rollup CLI with no problems at all. However, the example in this repo says

```js
import { rollup } from 'rollup';
import alias from 'rollup-plugin-alias';

rollup({
  entry: './src/index.js',
  plugins: [alias({
    somelibrary: './mylocallibrary'
  })],
});
```

how is this example supposed to be run? If I save it in a file `example.js` doing

```sh
node example.js
```

will throw:

```sh
(function (exports, require, module, __filename, __dirname) { import {
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

so, is it possible at all to `import` rollup, or it is meant to be used with node `require`?

**Comment by Rich-Harris** [comment]
I've updated the README so that it uses a [config file](https://rollupjs.org/#configuration-files). At the moment you're trying to run an ES module in Node, which isn't yet supported.
