### ISSUE TITLE
Can't make an alias that points towards a built-in node dependency

### ISSUE THREAD

**Issue by tex0l** [frostney/rollup-plugin-alias#33]
Hi,
Some of the packages (namely `from2` or `tar-stream`) I use use `readable-stream` which is a polyfill of the native node `stream`, and I want to use another polyfill (namely the ones used by `rollup-plugin-node-builtins`) since `readable-stream` doesn't work when packaging with rollup.

I wanted to use `rollup-plugin-alias` to replace programmatically every `require('readable-stream')` with `require('stream')`. But when I do that, I get this error:
```
[!] Error: Could not load stream (imported by /path/to/node_modules/from2/index.js): ENOENT: no such file or directory, open 'stream'
```

Apparently, I can't force `rollup-plugin-alias` not to resolve the paths, would it be possible to make an exception for node built-in modules ?

**Comment by tex0l** [comment]
As a workaround, I've come up with a very ugly hack using `rollup-plugin-replace` with this config:
```javascript
    replace({
      [`readable-stream`]: `require('stream')`,
      include: 'node_modules/from2/index.js',
      delimiters: ['require(\'', '\')']
    })
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
