### ISSUE TITLE
Should alias respect relative imports?

### ISSUE THREAD

**Issue by gaearon** [frostney/rollup-plugin-alias#34]
I bumped into an issue using this plugin for React.

If I alias `some-package/module` to a shim, direct imports of `some-package/module` are shimmed correctly.

However, I also assumed that `./module` import from `some-package/other-module` would also get shimmed. This was not the case.

I’m curious if you consider this a bug or if it works as designed. Perhaps our need to shim *a particular module* (no matter how it’s imported) would be better satisfied by a different plugin.

**Comment by gaearon** [comment]
FWIW I wrote a very simple plugin for myself that does what I need.

```js
function useForks(forks) {
  let resolvedForks = {};
  Object.keys(forks).forEach(srcModule => {
    const targetModule = forks[srcModule];
    resolvedForks[require.resolve(srcModule)] = require.resolve(targetModule);
  });
  return {
    resolveId(importee, importer) {
      if (!importer || !importee) {
        return null;
      }
      let resolvedImportee = null;
      try {
        resolvedImportee = require.resolve(importee, {
          paths: [path.dirname(importer)],
        });
      } catch (err) {
        // Not our fault, let Rollup fail later.
        return null;
      }
      if (resolvedForks.hasOwnProperty(resolvedImportee)) {
        // We found a fork!
        return resolvedForks[resolvedImportee];
      }
      return null;
    },
  };
}
```

Usage:

```js
useForks({
  'some-package/module': 'some-package/other-module'
})
```

Note it might not handle all valid edge cases etc.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
