### ISSUE TITLE
Paths starting with "../" point to the wrong directory.

### ISSUE THREAD

**Issue by ghost** [frostney/rollup-plugin-alias#36]
Given this structure:

```
package.json
dist/
    lib.es.js
test/
    index.js
    rollup.config.js
```

Where `index.js` imports `lib.es.js` using with `import lib from 'lib'`, running `rollup -c test/rollup.config.js` from the package root produces some weird results:

- With `alias({ lib: './dist/lib.es.js' })`, it resolves to `<pkg>/test/dist/lib.es.js` (testing 1..2..3)
- With `alias({ lib: './../dist/lib.es.js' })`, it resolves to `<pkg>/dist/lib.es.js` (ok, we got it)
- With `alias({ lib: '../dist/lib.es.js' })`, it resolves to `<pkg's parent>/dist/lib.es.js` (wut?!)

When you start the path with `../`, the "current directory" is no longer `test` but the package directory, causing the path to overshoot and resolve to the wrong path.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
