### ISSUE TITLE
Unexpected token = when importing 'rollup-plugin-alias' in Node v4

### ISSUE THREAD

**Issue by samoshkin** [frostney/rollup-plugin-alias#39]
So I have an import of this plugin in my rollup.config.js, without even using it yet.

```
import alias from 'rollup-plugin-alias';
```

And I get this error:
```
[!] SyntaxError: Unexpected token =
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions..js (/Users/asamoshkin/projects/pet/naive-weather-forecast/module/node_modules/rollup/bin/rollup:2752:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/asamoshkin/projects/pet/naive-weather-forecast/module/rollup.config.js:12:1)
    at Module._compile (module.js:435:26)
```

Looks like this plugin is distributed in a non transpiled form, I don't see any usage of `rollup-plugin-babel` or `rollup-plugin-buble` in [rollup.config.js](https://github.com/rollup/rollup-plugin-alias/blob/master/rollup.config.js). Other plugins do use transpilation, e.g [rollup-plugin-inject](https://github.com/rollup/rollup-plugin-inject/blob/master/rollup.config.js#L7)

So, Node v4 fails to run ES6 non transpiled version, whereas  Node >v5 runs fine, because it already have a proper support (maybe it's an arrow function or destructuring syntax, not sure).

```
nvm use v4
`npm bin`/rollup -c  // error as shown above

nvm use v5 | v6
`npm bin`/rollup -c  // works fine 
```

**Comment by F2EVarMan** [comment]
I have the same problem.
My Node version is v6.12.3

**Comment by F2EVarMan** [comment]
@samoshkin  Finally, I use 'rollup-plugin-alias 1.0.2'

**Comment by soanvig** [comment]
Why you use outdated software, like old `node` or old `rollup-plugin-alias`?

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
