### ISSUE TITLE
Please spell out what this plugin does in the usage example

### ISSUE THREAD

**Issue by callumlocke** [frostney/rollup-plugin-alias#4]
The readme's Usage section shows an example config for the plugin, but doesn't spell out what this config achieves. It would be good to spell it out with a sample entry script.

**Comment by frostney** [comment]
You're totally right. When I first created the section in the readme, it felt completely self-explainable to me, but going over it again, it seems more like that something's missing.

Thank you for bringing it up and creating the issue.

**Comment by teogeos** [comment]
I agree with this, it took me some time to understand what this plugin does when reading the readme, and I can only guess how the alias can be used in an import. It would also be nice to have an example showing how this can help to avoid writing '../../../'

**Comment by frostney** [comment]
I updated the readme with a code example. Please let me know if that is not clear enough.
