### ISSUE TITLE
Incorrect path

### ISSUE THREAD

**Issue by amsik** [frostney/rollup-plugin-alias#40]
Windows 10 allows you to open a directory in the console as follows:

``` bash
cd c:\your-module
```
`dir` command will show:

``` bash
> dir
 Volume in drive C has no label.

 Directory of c:\your-module
```
and a list of files.

In this way aliases don't work. Because appears the error:

``` shell
[!] Error: Could not load c:/your-module   ....
```

**But**, it works with real disk name (I mean in uppercased)

``` shell
cd C:\your-module
```
Really unexpected error :)

**Comment by soanvig** [comment]
First of all, Windows file system is case-insensitive. That's why your example from Windows console works.

Rollup uses node.js which is case-sensitive.

That's not `rollup-plugin-alias` bug, and support for that is - in my opinion - insignificant.

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
