### ISSUE TITLE
access alias key via rollup config module

### ISSUE THREAD

**Issue by sag1v** [frostney/rollup-plugin-alias#46]
Hi, in some cases i need to access the alias key (and get the value).
So when i do:
`import rollupCfg from './rollup.config';`

I would like to be able to get the value via
```rollupCfg.alias```
Or as `webpack` doing it (i think)
```rollupCfg.resolve.alias```

Is there any builtin way to do it currently?

**Comment by TriMoon** [comment]
If you export your key/values that you use in the call to the alias plugin in your `rollup.config`, it could be as simple as importing that named export from it... eg:
```js
// rollup.config.js
export const aliases = {
	someId: 'sompath'
	,someId2: 'sompath2'
}

const rollupcfg = {
	...
	,plugins: [
		...
		,alias(aliases)
		...
	]
}
export default rollupcfg
```
And then you can do:
```js
// yourmodule.mjs
import { aliases } from 'rollup.config'
for (let key in aliases) {
	const val = aliases[key]
	...
}
```

**Comment by shellscape** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @shellscape and request a re-open, and we'll be happy to oblige.
