### ISSUE TITLE
Not working with nodejs 6.x

### ISSUE THREAD

**Issue by ulrik59** [frostney/rollup-plugin-alias#5]
Hi,

I can't build my code when using nodejs 6.x. Here is the stack : 

``` shell
TypeError: Path must be a string. Received undefined
  at assertPath (path.js:7:11)
  at Object.dirname (path.js:1326:5)
  at /home/[...]/node_modules/rollup-plugin-alias/dist/rollup-plugin-alias.js:63:32
  at resolveId (/home/[...]/node_modules/rollup-plugin-alias/dist/rollup-plugin-alias.js:88:10)
  at /home/[...]/node_modules/rollup/dist/rollup.js:1574:32
  at process._tickCallback (internal/process/next_tick.js:103:7)

```

All is working fine with node 5.x
Thank you in advance

**Comment by ulrik59** [comment]
I figured what is happening. I have a directory named `app` where there is my application entry `app/index.js`. But in the `rollup-plugin-alias` configuration, I have the `app` directory configured as an alias. It allowed me to get `app/router.js` in the file `app/modules/mymodule/views/index.js` with

``` js
import 'app/router';
```

instead of

``` js
import '../../../../router';
```

The problem now is that the first call to : 

``` js
{
    resolveId: function (importee, importer) {}
}
```

has in arguments:

``` js
{ importee: 'app/index.js', importer: undefined }
```

In Node 5.12, the code below give `'.'`:

``` js
var directory = path.dirname(importer);
```

But in Node 6.x, it throw an exception.
I will eventually propose a PR when I have time.

**Comment by frostney** [comment]
Hi @ulrik59, did you run into this again? I have updated the Travis to run tests in Node.js 6 and 7 and I haven't run into this yet.

I'm closing this for now, but please re-open the issue if the issue still persists for you.
