### ISSUE TITLE
Doesn't play well with rollup-plugin-node-resolve

### ISSUE THREAD

**Issue by ghost** [frostney/rollup-plugin-alias#50]
I am trying to use both `rollup-plugin-node-resolve` and `rollup-plugin-alias` to allow me to do something like this:

```js
// rollup.config.js
export default {
  plugins: [
    resolve(),
    alias({
      '~': './'
    })
  ]
}
```

```js
// somefile.js
import dom from '~/dom';
```

Where the 'dom' directory contains an 'index.js' file that I'd like to be resolved automatically.  However, it's failing for me, saying that './dom.js' could not be resolved.

When I change the import line to `import dom from './dom';`, it resolves the index.js file correctly.

This indicates to me that `rollup-plugin-alias` is not connecting with `rollup-plugin-node-resolve` to grab the index file correctly.

I'm hoping this isn't a bug and that I'm just missing something, but in case I'm not I thought I'd point this out, as I'm sure it must be a common scenario.

**Comment by deavial** [comment]
in my project, I have resolve after alias and have it working.
