### ISSUE TITLE
It's working with rollup-plugin-typescript2?

### ISSUE THREAD

**Issue by viT-1** [frostney/rollup-plugin-alias#55]
Can't configure that combination for src/common.blocks alias ...

```
// src/tsconfig.json
"extends": "../tsproject.json",
"compilerOptions": {
	"baseUrl": ".",
	"paths": {
		"@common/*": [ "./common.blocks/*" ]
	}
}
```

**Comment by thiscantbeserious** [comment]
That's likely not related to this plugin. As per TS-Spec wildcards (similar to globs) are supported by default:

https://www.typescriptlang.org/docs/handbook/module-resolution.html

So you'll most likely want to go over to the rollup-plugin-typescript2 GIT repo and report your issue there, unless you can provide a minimal repo that outlines your above issues in combination with the alias plugin in specific.

Rollup plugins don't know each other - they only take an input and forward their output. The order or them is important - maybe your issue relates to that as well - but looking at the limited info you've given above I more or less expect the other plugin not working as expected (?).
