### ISSUE TITLE
alias node modules

### ISSUE THREAD

**Issue by johannes-z** [frostney/rollup-plugin-alias#56]
With webpack I could easily do this:

```
resolve.alias('@somescope/somelib', '@myscope/mylib')
```

I tried the same with `rollup-plugin-alias`:
```
alias({
  '@somescope/somelib': '@myscope/mylib'
})
```

but it doesn't do anything. If I leave out the whole rollup-alias block, it's still the same outcome.

The built bundle has this:
```
import * as SomeLib from '@somescope/somelib';
```

instead of

```
import * as SomeLib from '@myscope/mylib';
```

**Comment by thiscantbeserious** [comment]
> I tried the same with rollup-plugin-alias:
> 
> alias({
>   '@somescope/somelib': '@myscope/mylib'
> })

From Version 2 onwards this config is obsolete, the config now has to go into the entries property and the entries itself require an "find" and "replacement" property to work at all.

```
alias({entries:[
   {find:'@somescope/somelib', replacement:'@myscope/mylib'},
   {find:'@anotherscope/somelib', replacement:'@myscope/mylib'}
]})
```

Please see the Readme for distinct examples that might help you in what you want to achieve.

You can of course also point it towards the node_modules folder and use Regular Expressions with subpattern matching to do a complex search and replace. Your example is pretty unclear to me as such I can't help you any further with that.
