### ISSUE TITLE
Sapper path resolution conflict with components developed in Storybook

### ISSUE THREAD

**Issue by jerriclynsjohn** [frostney/rollup-plugin-alias#63]
My project uses storybook `webpack alias` and the main Sapper project uses `rollup-plugin-alias`. 

Consider this as my folder structure
```
src
|-- components
|   |-- atoms
|   |   `-- Button
|   |       |-- index.svelte
|   |       |-- index.stories.js
|   |       `-- index.md
|   `-- molecules
|       `-- PrimaryNavigation
|           |-- index.svelte
|           |-- index.stories.js
|           `-- index.md
`-- routes
    `-- index.svelte
```

In storybook while developing the UI components, I'm able to import components like this
```javascript
import Button from 'atoms/Button'
import PrimaryNavigation from 'molecules/PrimaryNavigation'
```
This is awesome, because here I'm not writing the whole path, but when compiling using rollup for the main project using `rollup-plugin-alias`, I get the following error.
```bash
Could not load C:\.............\src\components\atoms\Button.js (imported by C:\..........\src\routes\index.svelte): ENOENT: no such file or directory, open 'C:\..........\src\components\atoms\Button.js'
```

I was hoping that this plugin would atleast throw an error mentioning `*.svelte not found`

These are the configs used
1. `.storybook/webpack.config.js`
```javascript
module.exports = ({ config, mode }) => {

    const resolve = config.resolve;

    resolve.alias = {
        ...resolve.alias,
        atoms: path.resolve(__dirname, '../src/components/atoms'),
        molecules: path.resolve(__dirname, '../src/components/molecules'),
    };
    //The rest of the config
   ......
}
```

2. `rollup.config.js`
```javascript
import alias from 'rollup-plugin-alias';
.....
// rest of the imposts and consts
.....

const componentsFolder = `${__dirname}/src/components`;
const aliases = alias({
    resolve: ['.js', '.svelte'],
    entries: [
        { find: 'atoms', replacement: `${componentsFolder}/atoms` },
        { find: 'molecules', replacement: `${componentsFolder}/molecules` },
    ],
});

....
// Config consts
.....

export default {
    client: {
        input: config.client.input(),
        output: config.client.output(),
        plugins: [
            aliases,
            ....
            // rest of the plugins
            ......
        ],

    },

    server: {
        input: config.server.input(),
        output: config.server.output(),
        plugins: [
            aliases,
            ....
            // rest of the plugins
            ......
        ],
    },

    serviceworker: {
        // rest of the config
    },
};
```

**Expectation** is that this should behave the same in both the environment for a seamless development.

*Do you think I'm doing something wrong here*, why is it not resolving to `Button/index.svelte` because that's sort of an expected behavior in most environment especially with index.svelte

**Comment by jerriclynsjohn** [comment]
Currently I'm mentioning the whole path to resolve the issue, temporarily. I was hoping that there would be some sort of workaround for solving this.

**Comment by jerriclynsjohn** [comment]
Would it make sense to add a code [here ](https://github.com/rollup/rollup-plugin-alias/blob/fe3113b1ba9135d1c9cc36f6303c51513ebfea25/src/index.js#L65) that checks for the extension with default index.[resolve extensions] to resolve the path.

**Comment by jerriclynsjohn** [comment]
Just tried this fix on the above mentioned project, and it works!!!!! This is beautiful!!! :+1: :smile: :rocket:

**Comment by jnhooper** [comment]
try doing this
` resolve: ['.js', '.svelte', '/index.svelte'],`

**Comment by shellscape** [comment]
Closing, as there appears to be a fix.
